name: frontend
description: "LinguaSafeTrip - Multilingual Emergency Safety Assistant App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.6.1 # Keep current or update to latest stable
  riverpod_annotation: ^2.3.5 # User: ^2.3.0, Current: ^2.3.5. Keeping current.
  dio: ^5.4.3
  go_router: ^15.1.2
  shared_preferences: ^2.2.3
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.0
  flutter_markdown: ^0.7.1
  permission_handler: ^11.3.1
  connectivity_plus: ^6.0.3
  geolocator: ^12.0.0
  battery_plus: ^6.0.1
  uuid: ^4.4.0
  cupertino_icons: ^1.0.8
  flutter_gen: ^5.10.0
  freezed_annotation: ^2.4.1 # User: ^2.4.1
  json_annotation: ^4.9.0 # Keep current
  app_settings: ^5.1.1
  tuple: ^2.0.2 # For Tuple2 in chat history
  google_maps_flutter: ^2.6.1
  url_launcher: ^6.2.3
  speech_to_text: ^7.0.0
  path_provider: ^2.1.5
  record: ^5.2.1
  scrollable_positioned_list: ^0.3.8
  device_info_plus: ^10.1.0
  flutter_local_notifications: ^17.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Keep current or update
  build_runner: ^2.4.9 # User: ^2.4.9
  freezed: ^2.5.2 # User: ^2.4.1, using ^2.5.2 for Dart 3 compatibility
  riverpod_generator: ^2.4.0 # User: ^2.3.0, using ^2.4.0 as recent stable
  json_serializable: ^6.8.0 # User: ^6.8.0
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    # .envファイルは開発時のみ含める（本番ビルドでは除外）
    # 本番ビルド時は --dart-define を使用してセキュアに設定
    - .env
    - assets/icon/

dependency_overrides:
  record_linux: ^1.1.1
  record_platform_interface: ^1.3.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  
  # Android adaptive icon（背景を白に変更）
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/adaptive_icon_foreground.png"
  
  # iOS specific
  remove_alpha_ios: true
  
  # Web specific
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#FFD700"
    theme_color: "#1976D2"
  
  # Windows specific
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 256
  
  # macOS specific
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"
