"""
LinguaSafeTrip Prompts Module

Centralized location for all LLM prompt templates used throughout the application.
Follows CLAUDE.md guidelines for proper organization.
"""

# Main prompts
from .prompts import (
    SYSTEM_PROMPT_TEXT,
    INTENT_CLASSIFICATION_PROMPT_TEMPLATE,
    RESPONSE_SYNTHESIS_PROMPT_TEMPLATE,
    INFORMATION_GUIDE_RESPONSE_PROMPT_TEMPLATE,
    SUGGESTION_CARD_GENERATION_PROMPT_TEMPLATE,
    OFF_TOPIC_RESPONSE_PROMPT_TEMPLATE,
    PROACTIVE_SYSTEM_PROMPT_TEXT,
    # Suggestion prompts
    SUGGEST_EMERGENCY_CONTACT_SETUP_CARD_PROMPT_TEMPLATE,
    SUGGEST_SHELTER_CHECK_AFTER_ALERT_CARD_PROMPT_TEMPLATE,
    SUGGEST_ANNIVERSARY_PREPARATION_CARD_PROMPT_TEMPLATE,
    # Contact management prompts
    EXTRACT_CONTACT_INFO_PROMPT_TEMPLATE,
    CONFIRM_CONTACT_OPERATION_PROMPT_TEMPLATE,
    # Settings prompts
    EXPLAIN_SETTING_PROMPT_TEMPLATE,
    GUIDE_TO_SETTINGS_SCREEN_PROMPT_TEMPLATE,
    CONFIRM_SETTING_CHANGE_UNDERSTANDING_PROMPT_TEMPLATE
)

# Disaster-specific prompts
from .disaster_prompts import (
    BASE_PROMPT,
    ROUTING_SUPERVISOR_PROMPT,
    EVACUATION_ADVICE_PROMPT,
    EVACUATION_SUPPORT_RESPONSE_PROMPT,
    SHELTER_CARD_PROMPT,
    CHECKLIST_CARD_PROMPT,
    DISASTER_ANNIVERSARY_CARD_PROMPT,
    DISASTER_PROMPTS,
    PROACTIVE_PROMPT,
    get_disaster_prompt,
    get_proactive_prompt,
    get_evacuation_advice_prompt,
    get_evacuation_response_prompt,
    get_shelter_card_prompt,
    get_checklist_card_prompt,
    get_disaster_anniversary_card_prompt
)

__all__ = [
    # Main prompts
    "SYSTEM_PROMPT_TEXT",
    "INTENT_CLASSIFICATION_PROMPT_TEMPLATE", 
    "RESPONSE_SYNTHESIS_PROMPT_TEMPLATE",
    "INFORMATION_GUIDE_RESPONSE_PROMPT_TEMPLATE",
    "SUGGESTION_CARD_GENERATION_PROMPT_TEMPLATE",
    "OFF_TOPIC_RESPONSE_PROMPT_TEMPLATE",
    "PROACTIVE_SYSTEM_PROMPT_TEXT",
    "SUGGEST_EMERGENCY_CONTACT_SETUP_CARD_PROMPT_TEMPLATE",
    "SUGGEST_SHELTER_CHECK_AFTER_ALERT_CARD_PROMPT_TEMPLATE",
    "SUGGEST_ANNIVERSARY_PREPARATION_CARD_PROMPT_TEMPLATE",
    "EXTRACT_CONTACT_INFO_PROMPT_TEMPLATE",
    "CONFIRM_CONTACT_OPERATION_PROMPT_TEMPLATE",
    "EXPLAIN_SETTING_PROMPT_TEMPLATE",
    "GUIDE_TO_SETTINGS_SCREEN_PROMPT_TEMPLATE", 
    "CONFIRM_SETTING_CHANGE_UNDERSTANDING_PROMPT_TEMPLATE",
    
    # Disaster prompts
    "BASE_PROMPT",
    "ROUTING_SUPERVISOR_PROMPT",
    "EVACUATION_ADVICE_PROMPT",
    "EVACUATION_SUPPORT_RESPONSE_PROMPT",
    "SHELTER_CARD_PROMPT",
    "CHECKLIST_CARD_PROMPT",
    "DISASTER_ANNIVERSARY_CARD_PROMPT",
    "DISASTER_PROMPTS",
    "PROACTIVE_PROMPT",
    "get_disaster_prompt",
    "get_proactive_prompt",
    "get_evacuation_advice_prompt",
    "get_evacuation_response_prompt",
    "get_shelter_card_prompt",
    "get_checklist_card_prompt",
    "get_disaster_anniversary_card_prompt"
]